# Generated by Django 5.1.5 on 2025-03-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carehomes', to='cities_light.city')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_carehomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carers', to='MedTracker.carehome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_residents', models.BooleanField(default=False)),
                ('can_edit_medications', models.BooleanField(default=False)),
                ('can_view_inventory', models.BooleanField(default=True)),
                ('can_adjust_stock', models.BooleanField(default=False)),
                ('carer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='MedTracker.carer')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='MedTracker.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carehome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='MedTracker.carehome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nhs_id', models.CharField(default=None, max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.carehome')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection', 'Injection'), ('inhaled', 'Inhaled'), ('other', 'Other')], default='oral', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='MedTracker.medicationschedule')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.carer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.medicationschedule')),
                ('scheduled_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.medicationtime')),
            ],
            options={
                'ordering': ['-given_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='resident_photos/default.png', null=True, upload_to='resident_photos/')),
                ('conditions', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, help_text='List any known allergies')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='MedTracker.carehome')),
            ],
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.resident'),
        ),
        migrations.CreateModel(
            name='ResidentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(default='#FF0000', max_length=7)),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_groups', to='MedTracker.carehome')),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='MedTracker.residentgroup'),
        ),
        migrations.AddField(
            model_name='carer',
            name='resident_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carers', to='MedTracker.residentgroup'),
        ),
    ]
