# Generated by Django 5.1.5 on 2025-03-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='medicationschedule',
            name='dosage',
        ),
        migrations.CreateModel(
            name='MedicationInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('carehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedTracker.carehome')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='MedTracker.medication')),
            ],
            options={
                'unique_together': {('medication', 'dosage', 'form', 'carehome')},
            },
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='inventory_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedTracker.medicationinventoryitem'),
        ),
    ]
