# Generated by Django 5.1.5 on 2025-03-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedTracker', '0002_remove_medication_stock_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicationinventoryitem',
            unique_together={('medication', 'dosage', 'form')},
        ),
        migrations.RemoveField(
            model_name='medicationinventoryitem',
            name='carehome',
        ),
    ]
