# Generated by Django 5.1.5 on 2025-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTracker', '0003_alter_medicationinventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='access_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carer',
            name='indefinite_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carerpermissions',
            name='can_view_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
