# Generated by Django 5.1.5 on 2025-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTracker', '0004_carer_access_end_date_carer_indefinite_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, default='resident_photos/default.png', null=True, storage='MedTracker.encrypted_storage.EncryptedFileStorage', upload_to='resident_photos/'),
        ),
    ]
