# Generated by Django 5.1.5 on 2025-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTracker', '0005_alter_resident_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, default='resident_photos/default.png', null=True, upload_to='resident_photos/'),
        ),
    ]
